--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: messages; Type: TABLE; Schema: public; Owner: labuser
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    text character varying(255)
);


ALTER TABLE public.messages OWNER TO labuser;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: labuser
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: labuser
--

COPY public.messages (id, created_at, text) FROM stdin;
1	2026-08-09 11:07:32.002151+00	Hello From Verification Test
2	2026-08-09 11:07:32.591674+00	Consumed: Hello From Verification Test
3	2026-08-09 11:11:53.915719+00	This is test message sent at this time on Sunday 9-Aug-2026
4	2026-08-09 11:11:53.920944+00	Consumed: This is test message sent at this time on Sunday 9-Aug-2026
5	2026-08-09 11:41:53.603406+00	This is test message sent at this time on Sunday 9-Aug-2026
6	2026-08-09 11:41:53.960508+00	Consumed: This is test message sent at this time on Sunday 9-Aug-2026
7	2026-08-09 11:44:35.963317+00	another test
8	2026-08-09 11:44:35.975021+00	Consumed: another test
9	2026-08-09 11:46:01.049599+00	adfa
10	2026-08-09 11:46:01.061931+00	Consumed: adfa
11	2026-08-09 11:46:04.350152+00	234234
12	2026-08-09 11:46:04.353754+00	Consumed: 234234
13	2026-08-09 11:46:07.771366+00	adsfadsf asdf asdf qawesdfx
14	2026-08-09 11:46:07.775587+00	Consumed: adsfadsf asdf asdf qawesdfx
\.


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: labuser
--

SELECT pg_catalog.setval('public.messages_id_seq', 14, true);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: labuser
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

