grafana:
  adminPassword: admin
  plugins:
    - yesoreyeram-infinity-datasource
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    security:
      allow_embedding: true
  additionalDataSources:
    - name: Infinity
      type: yesoreyeram-infinity-datasource
      uid: infinity
      access: proxy
      isDefault: false
      jsonData:
        allowedHosts: []
  service:
    type: NodePort
    nodePort: 30000
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 768Mi
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
