apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lab
data:
  DB_HOST: postgres-postgresql
  DB_PORT: "5432"
  DB_NAME: labdb
  DB_USERNAME: labuser
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
