apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lab-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - lab
  selector:
    matchLabels:
      app: lab-app
  endpoints:
    - port: http
      interval: 15s
      path: /actuator/prometheus
